// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	domain "github.com/nicewook/gocore/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// OrderUseCase is an autogenerated mock type for the OrderUseCase type
type OrderUseCase struct {
	mock.Mock
}

type OrderUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderUseCase) EXPECT() *OrderUseCase_Expecter {
	return &OrderUseCase_Expecter{mock: &_m.Mock}
}

// CreateOrder provides a mock function with given fields: order
func (_m *OrderUseCase) CreateOrder(order *domain.Order) (*domain.Order, error) {
	ret := _m.Called(order)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *domain.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.Order) (*domain.Order, error)); ok {
		return rf(order)
	}
	if rf, ok := ret.Get(0).(func(*domain.Order) *domain.Order); ok {
		r0 = rf(order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(*domain.Order) error); ok {
		r1 = rf(order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderUseCase_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type OrderUseCase_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - order *domain.Order
func (_e *OrderUseCase_Expecter) CreateOrder(order interface{}) *OrderUseCase_CreateOrder_Call {
	return &OrderUseCase_CreateOrder_Call{Call: _e.mock.On("CreateOrder", order)}
}

func (_c *OrderUseCase_CreateOrder_Call) Run(run func(order *domain.Order)) *OrderUseCase_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.Order))
	})
	return _c
}

func (_c *OrderUseCase_CreateOrder_Call) Return(_a0 *domain.Order, _a1 error) *OrderUseCase_CreateOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderUseCase_CreateOrder_Call) RunAndReturn(run func(*domain.Order) (*domain.Order, error)) *OrderUseCase_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with no fields
func (_m *OrderUseCase) GetAll() ([]domain.Order, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Order
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Order, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Order); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Order)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderUseCase_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type OrderUseCase_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *OrderUseCase_Expecter) GetAll() *OrderUseCase_GetAll_Call {
	return &OrderUseCase_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *OrderUseCase_GetAll_Call) Run(run func()) *OrderUseCase_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OrderUseCase_GetAll_Call) Return(_a0 []domain.Order, _a1 error) *OrderUseCase_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderUseCase_GetAll_Call) RunAndReturn(run func() ([]domain.Order, error)) *OrderUseCase_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *OrderUseCase) GetByID(id int64) (*domain.Order, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (*domain.Order, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int64) *domain.Order); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderUseCase_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type OrderUseCase_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id int64
func (_e *OrderUseCase_Expecter) GetByID(id interface{}) *OrderUseCase_GetByID_Call {
	return &OrderUseCase_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *OrderUseCase_GetByID_Call) Run(run func(id int64)) *OrderUseCase_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *OrderUseCase_GetByID_Call) Return(_a0 *domain.Order, _a1 error) *OrderUseCase_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderUseCase_GetByID_Call) RunAndReturn(run func(int64) (*domain.Order, error)) *OrderUseCase_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderUseCase creates a new instance of OrderUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderUseCase {
	mock := &OrderUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
