// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	domain "github.com/nicewook/gocore/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// UserUseCase is an autogenerated mock type for the UserUseCase type
type UserUseCase struct {
	mock.Mock
}

type UserUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *UserUseCase) EXPECT() *UserUseCase_Expecter {
	return &UserUseCase_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: user
func (_m *UserUseCase) CreateUser(user *domain.User) (*domain.User, error) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.User) (*domain.User, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(*domain.User) *domain.User); ok {
		r0 = rf(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(*domain.User) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserUseCase_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type UserUseCase_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - user *domain.User
func (_e *UserUseCase_Expecter) CreateUser(user interface{}) *UserUseCase_CreateUser_Call {
	return &UserUseCase_CreateUser_Call{Call: _e.mock.On("CreateUser", user)}
}

func (_c *UserUseCase_CreateUser_Call) Run(run func(user *domain.User)) *UserUseCase_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.User))
	})
	return _c
}

func (_c *UserUseCase_CreateUser_Call) Return(_a0 *domain.User, _a1 error) *UserUseCase_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserUseCase_CreateUser_Call) RunAndReturn(run func(*domain.User) (*domain.User, error)) *UserUseCase_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with no fields
func (_m *UserUseCase) GetAll() ([]domain.User, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.User, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserUseCase_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type UserUseCase_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *UserUseCase_Expecter) GetAll() *UserUseCase_GetAll_Call {
	return &UserUseCase_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *UserUseCase_GetAll_Call) Run(run func()) *UserUseCase_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UserUseCase_GetAll_Call) Return(_a0 []domain.User, _a1 error) *UserUseCase_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserUseCase_GetAll_Call) RunAndReturn(run func() ([]domain.User, error)) *UserUseCase_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *UserUseCase) GetByID(id int64) (*domain.User, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (*domain.User, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int64) *domain.User); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserUseCase_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type UserUseCase_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id int64
func (_e *UserUseCase_Expecter) GetByID(id interface{}) *UserUseCase_GetByID_Call {
	return &UserUseCase_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *UserUseCase_GetByID_Call) Run(run func(id int64)) *UserUseCase_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *UserUseCase_GetByID_Call) Return(_a0 *domain.User, _a1 error) *UserUseCase_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserUseCase_GetByID_Call) RunAndReturn(run func(int64) (*domain.User, error)) *UserUseCase_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserUseCase creates a new instance of UserUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserUseCase {
	mock := &UserUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
