app:
  env: "dev"
  port: 8080
  debug: false
  log_level: "debug"

db:
  host: "localhost"
  port: 5432
  user: "dev_user"
  password: "dev_password"
  dbname: "dev_db"
  sslmode: "disable"

secure:
  cors_allow_origins:
    - "http://your.frontend.com"
    - "http://localhost:3000"
    - "http://localhost"